/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ValidationError {
  level: string
  category: string
  message: string
  path?: string
}
export interface ValidationResult {
  errors: Array<ValidationError>
  isValid: boolean
  errorCount: number
  warningCount: number
}
export declare function validateAll(dataDir: string, storesDir: string, schemasDir?: string | undefined | null): ValidationResult
/**
 * Validate the dataset after overlaying pending WebUI changes (mirrors the Python
 * `validate_all_with_changes`). `changes_json` is the `{ "changes": [...] }` payload.
 */
export declare function validateAllWithChanges(dataDir: string, storesDir: string, changesJson: string, schemasDir?: string | undefined | null): ValidationResult
export declare function validateJsonFiles(dataDir: string, storesDir: string, schemasDir?: string | undefined | null): ValidationResult
export declare function validateLogoFiles(dataDir: string, storesDir: string): ValidationResult
export declare function validateFolderNames(dataDir: string, storesDir: string): ValidationResult
export declare function validateStoreIds(dataDir: string, storesDir: string): ValidationResult
export declare function validateGtinEan(dataDir: string): ValidationResult
export declare function validateRequiredFiles(dataDir: string, storesDir: string): ValidationResult
export declare function validateLogoFile(logoPath: string, logoName?: string | undefined | null): ValidationResult
export declare function validateFolderName(folderPath: string, jsonFile: string, jsonKey: string): ValidationResult
export interface JsonFileInput {
  path: string
  schemaName: string
  content: string
}
export interface LogoFileInput {
  path: string
  filename: string
  content: Buffer
}
export interface FolderInput {
  path: string
  folderName: string
  jsonContent: string
  jsonKey: string
}
export interface SizesInput {
  path: string
  content: string
}
export interface ValidateAllContentInput {
  jsonFiles: Array<JsonFileInput>
  logoFiles: Array<LogoFileInput>
  folders: Array<FolderInput>
  storeIds: Array<string>
  schemas: Record<string, string>
}
export declare function validateJsonContent(content: string, schemaName: string, schemas: Record<string, string>, filePath?: string | undefined | null): ValidationResult
export declare function validateLogoContent(content: Buffer, filename: string, logoName?: string | undefined | null, filePath?: string | undefined | null): ValidationResult
export declare function validateFolderNameContent(folderName: string, jsonContent: string, jsonKey: string, filePath?: string | undefined | null): ValidationResult
export declare function validateGtinEanContent(sizesEntries: Array<SizesInput>): ValidationResult
export declare function validateStoreIdsContent(storeIds: Array<string>, sizesEntries: Array<SizesInput>): ValidationResult
export declare function validateAllContent(data: ValidateAllContentInput): ValidationResult
